export SignIn from './SignIn';
export SignUp from './signup';
export ProfileQuestionaire from './ProfileQuestionaire'
export Home from './Home'
export AdminHome from './Admin/AdminHome'
export adminSignIn from './Admin/adminSignIn'
export Comments from './Admin/Comments'
export RestaurantList from './Admin/restaurantList'
export Profile from './Profile'
